apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: npminstall
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: ARGS
          value: ["install"]

    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build
      taskRef:
        name: buildah
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/sn-labs-$(context.pipelineRun.namespace)/tax-calculator:latest"
