apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
