apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  params:
    - name: ARGS
      type: array
      description: The npm commands to execute
      default: ["install"]
  steps:
    - name: npm-run
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      command: ["npm"]
      args: ["$(params.ARGS)"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      command: ["npx"]
      args: ["jasmine"]
